# Generated by Django 5.1.2 on 2024-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
